apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-cert-prod
  namespace: istio-system
spec:
  secretName: kiali-cert-prod #use this secret in ingress gateway
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "kiali.arkainc.test.dev"
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io